<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         DB::table('menus')->insert([
            [
                'menu_name' => 'Lontong Opor Paha Atas',
                'stock' => 10,
                'price' => 25000,
                'discount' => 0,
                'description' => 'Lontong + opor paha atas + sambal',
                'image_path' => 'menus/lontong-opor-paha-atas.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Lontong Opor Paha Bawah',
                'stock' => 10,
                'price' => 23000,
                'discount' => 0,
                'description' => 'Lontong + opor paha bawah + sambal',
                'image_path' => 'menus/lontong-opor-paha-bawah.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Lontong Opor Sayap',
                'stock' => 10,
                'price' => 20000,
                'discount' => 0,
                'description' => 'Lontong + opor sayap ayam',
                'image_path' => 'menus/lontong-opor-sayap.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Lontong Opor Telor Koyor',
                'stock' => 8,
                'price' => 27000,
                'discount' => 0,
                'description' => 'Lontong + telur + koyor + sambal',
                'image_path' => 'menus/lontong-opor-telor-koyor.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Lontong Opor Telor Suwir',
                'stock' => 8,
                'price' => 25000,
                'discount' => 0,
                'description' => 'Lontong + telur + ayam suwir + sambal',
                'image_path' => 'menus/lontong-opor-telor-suwir.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Lontong Opor Telur',
                'stock' => 10,
                'price' => 20000,
                'discount' => 0,
                'description' => 'Lontong + opor telur + sambal',
                'image_path' => 'menus/lontong-opor-telur.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Nasi Gudeg Paha Atas',
                'stock' => 12,
                'price' => 30000,
                'discount' => 0,
                'description' => 'Nasi + gudeg + krecek + ayam paha atas',
                'image_path' => 'menus/nasi-gudeg-paha-atas.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Nasi Gudeg Paha Bawah',
                'stock' => 12,
                'price' => 29000,
                'discount' => 0,
                'description' => 'Nasi + gudeg + krecek + ayam paha bawah',
                'image_path' => 'menus/nasi-gudeg-paha-bawah.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Nasi Gudeg Sayap',
                'stock' => 12,
                'price' => 27000,
                'discount' => 0,
                'description' => 'Nasi + gudeg + krecek + ayam sayap',
                'image_path' => 'menus/nasi-gudeg-sayap.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Nasi Gudeg Telor Koyor',
                'stock' => 10,
                'price' => 30000,
                'discount' => 0,
                'description' => 'Nasi + gudeg + telur + koyor',
                'image_path' => 'menus/nasi-gudeg-telor-koyor.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Nasi Gudeg Telor Suwir',
                'stock' => 10,
                'price' => 20000,
                'discount' => 0,
                'description' => 'Nasi + gudeg + telur + ayam suwir',
                'image_path' => 'menus/nasi-gudeg-telor-suwir.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Nasi Gudeg Telur',
                'stock' => 20,
                'price' => 17000,
                'discount' => 0,
                'description' => 'Nasi + gudeg + telur + krecek',
                'image_path' => 'menus/nasi-gudeg-telur.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Nasi Liwet Paha Atas',
                'stock' => 10,
                'price' => 27000,
                'discount' => 0,
                'description' => 'Nasi liwet + ayam paha atas + telur',
                'image_path' => 'menus/nasi-liwet-paha-atas.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Nasi Liwet Paha Bawah',
                'stock' => 10,
                'price' => 25000,
                'discount' => 0,
                'description' => 'Nasi liwet + ayam paha bawah + telur',
                'image_path' => 'menus/nasi-liwet-paha-bawah.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Nasi Liwet Sayap',
                'stock' => 10,
                'price' => 23000,
                'discount' => 0,
                'description' => 'Nasi liwet + ayam sayap + telur',
                'image_path' => 'menus/nasi-liwet-sayap.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Nasi Liwet Telor Ayam Suwir',
                'stock' => 10,
                'price' => 20000,
                'discount' => 0,
                'description' => 'Nasi liwet + telur + ayam suwir',
                'image_path' => 'menus/nasi-liwet-telor-ayam-suwir.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Nasi Liwet Telor Koyor',
                'stock' => 10,
                'price' => 25000,
                'discount' => 0,
                'description' => 'Nasi liwet + telur + koyor',
                'image_path' => 'menus/nasi-liwet-telor-koyor.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'Nasi Liwet Telur',
                'stock' => 10,
                'price' => 17000,
                'discount' => 0,
                'description' => 'Nasi liwet + telur + sambal',
                'image_path' => 'menus/nasi-liwet-telur.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
